### ISSUE TITLE
shouldOverrideUrlLoading() 复写误用

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/CNode-OAuth-Login-Android#3]
使当前页面载入新的 URL，应在 shouldOverrideUrlLoading() 中返回 false，而不是调用 webView.loadUrl()

差别在于，返回 false，系统可以正确处理重定向等问题，而重新载入页面则不行。

**Comment by FITIMDOTORG** [comment]
The one that is new to the N Developer Preview has this method signature:

public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request)
The one that is supported by all Android versions, including N, has this method signature:

public boolean shouldOverrideUrlLoading(WebView view, String url)
so why should I do to make it work on all versions?

Override the deprecated one, the one that takes a String as the second parameter.
